# Generated by Django 5.0.4 on 2024-05-02 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_school_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='profile_image',
            field=models.ImageField(upload_to='schools/'),
        ),
    ]
