# Generated by Django 5.0.4 on 2024-05-12 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_formanswer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
