# Generated by Django 5.0.4 on 2024-05-04 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_website_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.RemoveField(
            model_name='school',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.RemoveField(
            model_name='website',
            name='user',
        ),
    ]
