# Generated by Django 5.0.4 on 2024-05-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_formanswer_form_remove_formanswer_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formanswerparent',
            name='levels',
            field=models.ManyToManyField(blank=True, null=True, to='api.level'),
        ),
    ]
