# Generated by Django 5.0.4 on 2024-05-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_product_user_remove_school_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='levels',
            field=models.ManyToManyField(blank=True, null=True, to='api.level'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='schools/'),
        ),
        migrations.AlterField(
            model_name='school',
            name='subjects',
            field=models.ManyToManyField(blank=True, null=True, to='api.subject'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='levels',
            field=models.ManyToManyField(blank=True, null=True, to='api.level'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='teachers/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, null=True, to='api.subject'),
        ),
    ]
