# Generated by Django 5.0.4 on 2024-05-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_formanswerparent_levels_form_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='is_student_information',
            field=models.BooleanField(default=False),
        ),
    ]
