# Generated by Django 5.0.4 on 2024-05-06 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_form_formtype_formapplication_formfield_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='type',
            field=models.CharField(choices=[('text', 'text'), ('number', 'number'), ('email', 'email'), ('date', 'date'), ('time', 'time'), ('checkbox', 'checkbox'), ('textarea', 'textarea'), ('file', 'file')], default='text', max_length=100, null=True),
        ),
    ]
