# Generated by Django 5.0.4 on 2024-05-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_student_birth_date_alter_student_levels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(max_length=20),
        ),
    ]
